package com.pluxity.aiot.eds

enum class EdsEventType(
    val code: Int,
    val description: String,
) {
    LOITERING(0, "배회"),
    PATH_PASS(1, "경로통과"),
    DIRECTIONAL_MOVE(2, "방향성이동"),
    ENTER(3, "진입"),
    EXIT(4, "진출"),
    STOP(5, "멈춤"),
    ABANDONED(6, "버려짐"),
    LINE_CROSS(7, "경계선통과"),
    SMOKE(8, "연기"),
    FLAME(9, "불꽃"),
    FALL_DOWN(10, "쓰러짐"),
    CROWD(11, "군집"),
    VIOLENCE(12, "폭력"),
    MULTI_LINE_CROSS(13, "멀티경계선통과"),
    VEHICLE_ACCIDENT(14, "차량사고"),
    VEHICLE_STOP(15, "차량멈춤"),
    TRAFFIC_JAM(16, "교통정체"),
    COLOR_CHANGE(17, "색상변화"),
    VEHICLE_PARKING(18, "차량주차"),
    REMOVED(19, "제거됨"),
    DANGER_WATER_LEVEL(20, "위험수위"),
    AREA_COLOR(21, "영역색상"),
    STAY(22, "체류"),
    STAY_OVERCROWDED(23, "체류-초과인원"),
    STAY_TIMEOUT(24, "체류-시간초과"),
    STAY_ALONE(25, "체류-단독인원체류"),
    NO_HELMET(26, "안전모미착용"),
    LEFT_ALONE(29, "홀로남겨짐"),
    APPROACH(30, "접근"),
    SEPARATE(31, "따로떨어짐"),
    ACTION_RECOGNITION(32, "행동인식"),
    VEHICLE_TAILGATING(33, "차량꼬리물기"),
    JAYWALKING(35, "무단횡단"),
    FARE_EVASION(36, "부정승차"),
    NO_MASK(37, "마스크미착용"),
    NO_SAFETY_VEST(38, "안전조끼미착용"),
    PEDESTRIAN_DANGER(43, "보행자위험"),
    PEDESTRIAN_STATISTICS(46, "보행자통계"),
    FLASHLIGHT(47, "손전등점등"),
    LICENSE_PLATE_RECOGNITION(48, "번호인식"),
    GAUGE_RECOGNITION(49, "게이지인식"),
    CAKE_RECOGNITION(50, "케이크인식"),
    SAFETY_HOOK_UNLATCHED(54, "안전고리미체결"),
    NO_KORAIL_UNIFORM(55, "코레일작업복미착용"),
    CROWD_DENSITY(56, "군중밀도"),
    FACE_RECOGNITION(57, "얼굴인식"),
    VEHICLE_PLATE(58, "차량번호판"),
    WEAPON_THREAT(59, "흉기위협"),
    ;

    companion object {
        fun fromCode(code: Int): EdsEventType? = entries.find { it.code == code }
    }
}
