-- 새 코드 배포 전에 실행한다. 배포가 먼저면 Hibernate가 action_history.incident_id NOT NULL 추가에 실패한다.

BEGIN;

CREATE TABLE IF NOT EXISTS incident (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6) NOT NULL,
    updated_at     timestamp(6) NOT NULL,
    created_by     varchar(255),
    updated_by     varchar(255),
    source_type    varchar(255) NOT NULL,
    source_id      bigint       NOT NULL,
    site_id        bigint REFERENCES site (id),
    device_id      varchar(255) NOT NULL,
    device_name    varchar(255),
    title          varchar(255) NOT NULL,
    level          varchar(255) NOT NULL,
    occurred_at    timestamp(6) NOT NULL,
    latitude       float(53),
    longitude      float(53),
    guide_message  varchar(255),
    status         varchar(255) NOT NULL,
    resolved_at    timestamp(6),
    CONSTRAINT incident_uk_source UNIQUE (source_type, source_id)
);
CREATE INDEX IF NOT EXISTS incident_idx_status_id ON incident (status, id);
CREATE INDEX IF NOT EXISTS incident_idx_site_occurred_at ON incident (site_id, occurred_at);

-- title은 DeviceProfileEnum.description과 같아야 한다
INSERT INTO incident (created_at, updated_at, created_by, updated_by,
                      source_type, source_id, site_id, device_id, device_name, title, level,
                      occurred_at, latitude, longitude, guide_message, status, resolved_at)
SELECT e.created_at,
       e.updated_at,
       e.created_by,
       e.updated_by,
       'SENSOR',
       e.id,
       f.site_id,
       e.device_id,
       e.sensor_description,
       CASE e.field_key
           WHEN 'Temperature'       THEN '온도'
           WHEN 'Humidity'          THEN '습도'
           WHEN 'Fire Alarm'        THEN '화재감지'
           WHEN 'DiscomfortIndex'   THEN '불쾌지수'
           WHEN 'ContainerModuleId' THEN '쓰레기통 모듈 번호'
           WHEN 'ActualFilling'     THEN '감지된 적재높이'
           WHEN 'FireDetection'     THEN '산불 감지'
           WHEN 'CO2'               THEN '이산화탄소'
           WHEN 'CO'                THEN '일산화탄소'
           WHEN 'TVOC'              THEN '휘발성유기화합물'
           WHEN 'FireCauseMask'     THEN '산불 원인'
           WHEN 'NH3'               THEN '암모니아'
           WHEN 'H2S'               THEN '황화수소'
           WHEN 'NumberOfVisitors'  THEN '입장객수'
           WHEN 'NumberOfLeavers'   THEN '퇴장객수'
           WHEN 'PM2.5'             THEN '초미세먼지'
           WHEN 'PM10'              THEN '미세먼지'
           WHEN 'WindSpeed'         THEN '풍속'
           WHEN 'WindDirection'     THEN '풍향'
           WHEN 'UVI'               THEN '자외선 지수'
           WHEN 'LED Light'         THEN 'LED 램프'
           WHEN 'HighThreshold'     THEN '만재 여부 판단 기준값'
           ELSE e.field_key
       END,
       COALESCE(e.level, 'WARNING'),
       e.occurred_at,
       COALESCE(e.latitude, f.latitude),
       COALESCE(e.longitude, f.longitude),
       e.guide_message,
       COALESCE(e.status, 'ACTIVE'),
       CASE WHEN e.status = 'RESOLVED' THEN e.updated_at END
FROM event_history e
LEFT JOIN feature f ON f.device_id = e.device_id
WHERE NOT EXISTS (SELECT 1 FROM incident i WHERE i.source_type = 'SENSOR' AND i.source_id = e.id);

ALTER TABLE action_history ADD COLUMN IF NOT EXISTS incident_id bigint;

UPDATE action_history a
SET incident_id = i.id
FROM incident i
WHERE i.source_type = 'SENSOR'
  AND i.source_id = a.event_history_id
  AND a.incident_id IS NULL;

ALTER TABLE action_history ALTER COLUMN incident_id SET NOT NULL;
ALTER TABLE action_history
    ADD CONSTRAINT fk_action_history_incident FOREIGN KEY (incident_id) REFERENCES incident (id);
ALTER TABLE action_history DROP COLUMN event_history_id;

DROP INDEX IF EXISTS event_history_idx_event_status_id_desc;
ALTER TABLE event_history DROP COLUMN IF EXISTS status;

COMMIT;
