-- Hibernate 7.4 PostgreSQL 방언으로 엔티티에서 생성한 baseline (incident 도입 직전 스키마)
-- 기존 DB는 baseline-on-migrate로 이 버전을 건너뛴다
CREATE EXTENSION IF NOT EXISTS postgis;

create table action_history (
    created_at timestamp(6) not null,
    event_history_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    content varchar(255),
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table action_history_file (
    action_history_id bigint not null,
    file_id bigint not null,
    id bigint generated by default as identity,
    primary key (id)
);

create table announcement (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint not null,
    updated_at timestamp(6) not null,
    message varchar(1000),
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table cctv (
    camera_analysis_configured integer,
    camera_port integer,
    camera_record_type integer,
    latitude float(53),
    longitude float(53),
    ptz_control integer,
    stream_resolution_height integer,
    stream_resolution_width integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint,
    updated_at timestamp(6) not null,
    camera_address varchar(255),
    camera_ip varchar(255),
    camera_status varchar(255) check ((camera_status in ('DISCONNECTED','NORMAL','FAULT'))),
    camera_type varchar(255) check ((camera_type in ('IP','VIDEO','PTZ','AIBOX','AI','UNMANAGED','UNSUPPORTED'))),
    created_by varchar(255),
    eds_camera_id varchar(255) not null unique,
    name varchar(255),
    updated_by varchar(255),
    geom geometry(Point, 4326),
    primary key (id)
);

create table eds_event (
    event_id integer not null,
    event_zone_id integer,
    latitude float(53),
    longitude float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    index bigint not null unique,
    thumbnail_file_id bigint,
    updated_at timestamp(6) not null,
    camera_id varchar(255),
    created_by varchar(255),
    detected_vehicle_number varchar(255),
    event_end varchar(255),
    event_start varchar(255),
    event_status varchar(255) check ((event_status in ('STARTED','IN_PROGRESS','ENDED'))),
    event_type varchar(255) check ((event_type in ('LOITERING','PATH_PASS','DIRECTIONAL_MOVE','ENTER','EXIT','STOP','ABANDONED','LINE_CROSS','SMOKE','FLAME','FALL_DOWN','CROWD','VIOLENCE','MULTI_LINE_CROSS','VEHICLE_ACCIDENT','VEHICLE_STOP','TRAFFIC_JAM','COLOR_CHANGE','VEHICLE_PARKING','REMOVED','DANGER_WATER_LEVEL','AREA_COLOR','STAY','STAY_OVERCROWDED','STAY_TIMEOUT','STAY_ALONE','NO_HELMET','LEFT_ALONE','APPROACH','SEPARATE','ACTION_RECOGNITION','VEHICLE_TAILGATING','JAYWALKING','FARE_EVASION','NO_MASK','NO_SAFETY_VEST','PEDESTRIAN_DANGER','PEDESTRIAN_STATISTICS','FLASHLIGHT','LICENSE_PLATE_RECOGNITION','GAUGE_RECOGNITION','CAKE_RECOGNITION','SAFETY_HOOK_UNLATCHED','NO_KORAIL_UNIFORM','CROWD_DENSITY','FACE_RECOGNITION','VEHICLE_PLATE','WEAPON_THREAT'))),
    event_zone_name varchar(255),
    frame_time varchar(255),
    profile_name varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table event_history (
    latitude float(53),
    longitude float(53),
    max_value float(53),
    min_value float(53),
    value float(53) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    device_id varchar(255) not null,
    event_name varchar(255) not null,
    field_key varchar(255) not null,
    guide_message varchar(255),
    level varchar(255) check ((level in ('NORMAL','WARNING','CAUTION','DANGER','DISCONNECTED'))),
    object_id varchar(255) not null,
    sensor_description varchar(255) not null,
    status varchar(255) check ((status in ('ACTIVE','IN_PROGRESS','RESOLVED'))),
    unit varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table event_condition (
    boolean_value boolean,
    is_active boolean,
    left_value float(53),
    notification_enabled boolean not null,
    right_value float(53),
    threshold_value float(53),
    id bigint generated by default as identity,
    condition_type varchar(255) check ((condition_type in ('SINGLE','RANGE'))),
    field_key varchar(255) not null,
    guide_message varchar(255),
    level varchar(255) not null check ((level in ('NORMAL','WARNING','CAUTION','DANGER','DISCONNECTED'))),
    object_id varchar(255) not null,
    operator varchar(255) check ((operator in ('GE','LE','BETWEEN'))),
    primary key (id)
);

create table feature (
    battery_level integer,
    height float(53),
    is_active boolean not null,
    latitude float(53),
    longitude float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint,
    subscription_time timestamp(6),
    updated_at timestamp(6) not null,
    event_status varchar(50),
    created_by varchar(255),
    device_id varchar(255) not null unique,
    name varchar(255),
    object_id varchar(255) not null,
    updated_by varchar(255),
    geom geometry(Point, 4326),
    primary key (id)
);

create table files (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    content_type varchar(255) not null,
    created_by varchar(255),
    file_path varchar(255) not null unique,
    file_status varchar(255) not null check ((file_status in ('TEMP','COMPLETE'))),
    original_file_name varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table llm_message (
    today_avg_temp float(53) not null,
    yesterday_avg_temp float(53) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint not null,
    updated_at timestamp(6) not null,
    prompt varchar(500) not null,
    message varchar(1000) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table mic (
    latitude float(53),
    longitude float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    edge_id varchar(255),
    host varchar(255),
    name varchar(255),
    status varchar(255) check ((status in ('ACTIVE','INACTIVE','DISCONNECTED'))),
    updated_by varchar(255),
    vendor_mic_id varchar(255) not null unique,
    geom geometry(Point, 4326),
    thresholds jsonb,
    primary key (id)
);

create table mic_event (
    avg_noise float(53),
    confidence float(53),
    latitude float(53),
    longitude float(53),
    max_noise float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    event_id varchar(255) not null unique,
    label_id varchar(255),
    label_name_en varchar(255),
    label_name_ko varchar(255),
    mic_id varchar(255) not null,
    mic_name varchar(255),
    updated_by varchar(255),
    noises jsonb,
    primary key (id)
);

create table mobius_config (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    url VARCHAR(255) DEFAULT 'http://203.253.128.181:11000/Mobius/sawwave' not null,
    primary key (id)
);

create table permission (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    permission_group_id bigint,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    resource_id varchar(255) not null,
    resource_name varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table permission_group (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    description varchar(255),
    name varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table role_permission (
    id bigint generated by default as identity,
    permission_group_id bigint,
    role_id bigint,
    primary key (id)
);

create table roles (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    description varchar(100),
    auth varchar(255),
    created_by varchar(255),
    name varchar(255) not null unique,
    updated_by varchar(255),
    primary key (id)
);

create table site (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    thumbnail_id bigint,
    updated_at timestamp(6) not null,
    name varchar(50) not null,
    created_by varchar(255),
    description varchar(255),
    updated_by varchar(255),
    location geometry(Polygon, 4326),
    primary key (id)
);

create table site_sensor_manager (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    sensor_type varchar(50) not null check ((sensor_type in ('TEMPERATURE_HUMIDITY','FIRE','WASTE_FILL_LEVEL','FOREST_FIRE','ODOR_MONITOR','PEOPLE_COUNTER','COMPOSITE_AIR_QUALITY'))),
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id),
    unique (site_id, sensor_type, user_id)
);

create table sms_history (
    result_code integer,
    stat_code integer,
    status_code integer,
    clidx bigint,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    result_checked_at timestamp(6),
    updated_at timestamp(6) not null,
    sender_number varchar(40),
    target_number varchar(40) not null,
    failure_reason varchar(1000),
    message varchar(2000) not null,
    created_by varchar(255),
    error_code varchar(255),
    message_type varchar(255),
    result varchar(255) check ((result in ('SUCCESS','FAILURE'))),
    stat varchar(255) not null check ((stat in ('SUCCESS','NO_ACCOUNT','NUMBER_TOO_LONG','NOT_SENT'))),
    status varchar(255) check ((status in ('COMPLETED','CANCELED','ERROR'))),
    title varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create table user_role (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    role_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_password_change_date timestamp(6),
    updated_at timestamp(6) not null,
    code varchar(20),
    name varchar(20) not null,
    created_by varchar(255),
    department varchar(255),
    password varchar(255) not null,
    phone_number varchar(255),
    updated_by varchar(255),
    username varchar(255) not null unique,
    primary key (id)
);

create index IDX8r2tnvebl2vcvq5yc4radeaoa 
   on eds_event (event_id);

create index event_history_idx_event_status_id_desc 
   on event_history (status, id);

create index IDXebddqhk68nkm8dk2k9vt869sw 
   on mic_event (mic_id);

create index IDX3njroyg3iys5rfgoyt9apaeg3 
   on mic_event (occurred_at);

create index IDXssxhdvbnyude0x8x7lqgi4cvc 
   on sms_history (clidx);

create index IDXp2gemepf0p9alr21vaygabkfh 
   on sms_history (created_at);

alter table if exists action_history 
   add constraint FKiib8k455x8nj9v72mw1ktekck 
   foreign key (event_history_id) 
   references event_history;

alter table if exists action_history_file 
   add constraint FKgx0y2j2f9pyrd97g13gk3a7y4 
   foreign key (action_history_id) 
   references action_history;

alter table if exists announcement 
   add constraint FKile8m80vm55r6jpharyyl6c0a 
   foreign key (site_id) 
   references site;

alter table if exists cctv 
   add constraint FK9s6g8iyqjon6d2k0qtwh8t8yp 
   foreign key (site_id) 
   references site;

alter table if exists feature 
   add constraint FK9mvamw946qtf8y6rpyae5c1ee 
   foreign key (site_id) 
   references site;

alter table if exists llm_message 
   add constraint FK2007dxf1su46an8raqc7n6d10 
   foreign key (site_id) 
   references site;

alter table if exists mic 
   add constraint FKg40f3l1of8n1jjr733c7syrlu 
   foreign key (site_id) 
   references site;

alter table if exists permission 
   add constraint FKtqibh46a99ho0ooxbqphdi2js 
   foreign key (permission_group_id) 
   references permission_group;

alter table if exists role_permission 
   add constraint FKnr0lm5yl4iheelgflwyfgrbrv 
   foreign key (permission_group_id) 
   references permission_group;

alter table if exists role_permission 
   add constraint FKtfgq8q9blrp0pt1pvggyli3v9 
   foreign key (role_id) 
   references roles;

alter table if exists site_sensor_manager 
   add constraint FK35u3sd5cn79uptlewrokb61uv 
   foreign key (site_id) 
   references site;

alter table if exists site_sensor_manager 
   add constraint FKqrcxii355qgfqmk9lwovqh39b 
   foreign key (user_id) 
   references users;

alter table if exists user_role 
   add constraint FKt7e7djp752sqn6w22i6ocqy6q 
   foreign key (role_id) 
   references roles;

alter table if exists user_role 
   add constraint FKj345gk1bovqvfame88rcx7yyx 
   foreign key (user_id) 
   references users;
