-- 센서·CCTV·AI마이크 이벤트 통합 관리 테이블. 기존 센서 이벤트를 백필하고 조치 상태를 incident로 옮긴다
create table incident (
    latitude float(53),
    longitude float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    resolved_at timestamp(6),
    site_id bigint,
    source_id bigint not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    device_id varchar(255) not null,
    device_name varchar(255),
    guide_message varchar(255),
    level varchar(255) not null check ((level in ('NORMAL','WARNING','CAUTION','DANGER','DISCONNECTED'))),
    source_type varchar(255) not null check ((source_type in ('SENSOR','CCTV','MIC'))),
    status varchar(255) not null check ((status in ('ACTIVE','IN_PROGRESS','RESOLVED'))),
    title varchar(255) not null,
    updated_by varchar(255),
    primary key (id),
    constraint incident_uk_source unique (source_type, source_id)
);

create index incident_idx_status_id on incident (status, id);
create index incident_idx_site_occurred_at on incident (site_id, occurred_at);

alter table if exists incident
    add constraint FKkuxax6sphyl9mijsal2jeylpe foreign key (site_id) references site;

INSERT INTO incident (created_at, updated_at, created_by, updated_by,
                      source_type, source_id, site_id, device_id, device_name, title, level,
                      occurred_at, latitude, longitude, guide_message, status, resolved_at)
SELECT e.created_at,
       e.updated_at,
       e.created_by,
       e.updated_by,
       'SENSOR',
       e.id,
       f.site_id,
       e.device_id,
       e.sensor_description,
       CASE e.field_key
           WHEN 'Temperature'       THEN '온도'
           WHEN 'Humidity'          THEN '습도'
           WHEN 'Fire Alarm'        THEN '화재감지'
           WHEN 'DiscomfortIndex'   THEN '불쾌지수'
           WHEN 'ContainerModuleId' THEN '쓰레기통 모듈 번호'
           WHEN 'ActualFilling'     THEN '감지된 적재높이'
           WHEN 'FireDetection'     THEN '산불 감지'
           WHEN 'CO2'               THEN '이산화탄소'
           WHEN 'CO'                THEN '일산화탄소'
           WHEN 'TVOC'              THEN '휘발성유기화합물'
           WHEN 'FireCauseMask'     THEN '산불 원인'
           WHEN 'NH3'               THEN '암모니아'
           WHEN 'H2S'               THEN '황화수소'
           WHEN 'NumberOfVisitors'  THEN '입장객수'
           WHEN 'NumberOfLeavers'   THEN '퇴장객수'
           WHEN 'PM2.5'             THEN '초미세먼지'
           WHEN 'PM10'              THEN '미세먼지'
           WHEN 'WindSpeed'         THEN '풍속'
           WHEN 'WindDirection'     THEN '풍향'
           WHEN 'UVI'               THEN '자외선 지수'
           WHEN 'LED Light'         THEN 'LED 램프'
           WHEN 'HighThreshold'     THEN '만재 여부 판단 기준값'
           ELSE e.field_key
       END,
       COALESCE(e.level, 'WARNING'),
       e.occurred_at,
       COALESCE(e.latitude, f.latitude),
       COALESCE(e.longitude, f.longitude),
       e.guide_message,
       COALESCE(e.status, 'ACTIVE'),
       CASE WHEN e.status = 'RESOLVED' THEN e.updated_at END
FROM event_history e
LEFT JOIN feature f ON f.device_id = e.device_id
WHERE NOT EXISTS (SELECT 1 FROM incident i WHERE i.source_type = 'SENSOR' AND i.source_id = e.id);

ALTER TABLE action_history ADD COLUMN IF NOT EXISTS incident_id bigint;

UPDATE action_history a
SET incident_id = i.id
FROM incident i
WHERE i.source_type = 'SENSOR'
  AND i.source_id = a.event_history_id
  AND a.incident_id IS NULL;

ALTER TABLE action_history ALTER COLUMN incident_id SET NOT NULL;
ALTER TABLE action_history
    ADD CONSTRAINT FK7k0wpa6capjrc60vh42cri3kj FOREIGN KEY (incident_id) REFERENCES incident (id);
ALTER TABLE action_history DROP COLUMN event_history_id;

DROP INDEX IF EXISTS event_history_idx_event_status_id_desc;
ALTER TABLE event_history DROP COLUMN IF EXISTS status;
