-- ddl-auto update 시절 배포되지 않은 채 baseline 처리된 운영 DB에 V1 테이블 일부가 없다.
-- 이미 있는 DB에서는 그대로 지나가도록 전부 if not exists 로 만든다.

create table if not exists mic (
    latitude float(53),
    longitude float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    edge_id varchar(255),
    host varchar(255),
    name varchar(255),
    status varchar(255) check ((status in ('ACTIVE','INACTIVE','DISCONNECTED'))),
    updated_by varchar(255),
    vendor_mic_id varchar(255) not null unique,
    geom geometry(Point, 4326),
    thresholds jsonb,
    primary key (id)
);

create table if not exists mic_event (
    avg_noise float(53),
    confidence float(53),
    latitude float(53),
    longitude float(53),
    max_noise float(53),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    event_id varchar(255) not null unique,
    label_id varchar(255),
    label_name_en varchar(255),
    label_name_ko varchar(255),
    mic_id varchar(255) not null,
    mic_name varchar(255),
    updated_by varchar(255),
    noises jsonb,
    primary key (id)
);

create table if not exists site_sensor_manager (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    site_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    sensor_type varchar(50) not null check ((sensor_type in ('TEMPERATURE_HUMIDITY','FIRE','WASTE_FILL_LEVEL','FOREST_FIRE','ODOR_MONITOR','PEOPLE_COUNTER','COMPOSITE_AIR_QUALITY'))),
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id),
    unique (site_id, sensor_type, user_id)
);

create table if not exists sms_history (
    result_code integer,
    stat_code integer,
    status_code integer,
    clidx bigint,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    result_checked_at timestamp(6),
    updated_at timestamp(6) not null,
    sender_number varchar(40),
    target_number varchar(40) not null,
    failure_reason varchar(1000),
    message varchar(2000) not null,
    created_by varchar(255),
    error_code varchar(255),
    message_type varchar(255),
    result varchar(255) check ((result in ('SUCCESS','FAILURE'))),
    stat varchar(255) not null check ((stat in ('SUCCESS','NO_ACCOUNT','NUMBER_TOO_LONG','NOT_SENT'))),
    status varchar(255) check ((status in ('COMPLETED','CANCELED','ERROR'))),
    title varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
);

create index if not exists IDXebddqhk68nkm8dk2k9vt869sw on mic_event (mic_id);
create index if not exists IDX3njroyg3iys5rfgoyt9apaeg3 on mic_event (occurred_at);
create index if not exists IDXssxhdvbnyude0x8x7lqgi4cvc on sms_history (clidx);
create index if not exists IDXp2gemepf0p9alr21vaygabkfh on sms_history (created_at);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkg40f3l1of8n1jjr733c7syrlu') then
        alter table mic add constraint FKg40f3l1of8n1jjr733c7syrlu foreign key (site_id) references site;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk35u3sd5cn79uptlewrokb61uv') then
        alter table site_sensor_manager add constraint FK35u3sd5cn79uptlewrokb61uv foreign key (site_id) references site;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fkqrcxii355qgfqmk9lwovqh39b') then
        alter table site_sensor_manager add constraint FKqrcxii355qgfqmk9lwovqh39b foreign key (user_id) references users;
    end if;
end $$;
