create table speaker_preset (
    repeat_count integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    title varchar(50) not null,
    message varchar(1000) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);
